version: "2"
services:
  larry_agent:
    build:
      context: ./consul
      args:
        - http_proxy=${local_proxy}
        - https_proxy=${local_proxy}
    image: jamtur01/consul
    hostname: larry
    container_name: larry_agent
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8500:8500"
      - "53:53/udp"
    command: ["-server", "-advertise=10.10.10.11", "-bootstrap-expect=3", "-ui"]

  larry_distributed:
    build:
      context: ./distributed_app
      args:
        - http_proxy=${local_proxy}
        - https_proxy=${local_proxy}
    image: jamtur01/distributed_app
    hostname: larry
    container_name: larry_distributed
    depends_on:
      - larry_agent