version: "2"
services:
  moe_agent:
    build:
      context: ./consul
      args:
        - http_proxy=${local_proxy}
        - https_proxy=${local_proxy}
    image: jamtur01/consul
    hostname: moe
    container_name: moe_agent
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8500:8500"
      - "53:53/udp"
    command: ["-server", "-advertise=10.10.10.13", "-join=10.10.10.11", "-ui"]

  moe_distributed:
    build:
      context: ./distributed_client
      args:
        - http_proxy=${local_proxy}
        - https_proxy=${local_proxy}
    image: jamtur01/distributed_client
    hostname: moe
    container_name: moe_distributed
    depends_on:
      - moe_agent